/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 AirPurifier.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function AirPurifier(props) {
  const { nodes, materials } = useGLTF('/AirPurifier.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.002']} position={[0, 0, 0.079]} rotation={[-0.046, 0, 0]} scale={0.019} />
      <group position={[0.148, 0.205, 0.003]}>
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials['white.002']} />
      </group>
      <group position={[0.134, 0.205, 0.003]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['white.003']} />
      </group>
      <group position={[0.121, 0.205, 0.003]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['white.002']} />
      </group>
      <group position={[0.108, 0.205, 0.003]}>
        <mesh geometry={nodes.Cube007.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['white.002']} />
      </group>
      <group position={[0.125, 0.166, 0]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['white.001']} />
      </group>
      <mesh geometry={nodes['6'].geometry} material={materials['6']} position={[0, 0.001, 0.098]} rotation={[1.525, 0, 0]} scale={0.042} />
      <mesh geometry={nodes.path9279.geometry} material={materials['SVGMat.001']} position={[-0.042, 0.031, 0.094]} rotation={[Math.PI / 2, 0, 0]} scale={0.294} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.white} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.black} />
    </group>
  )
}

useGLTF.preload('/AirPurifier.glb')
