/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 heater.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Heater(props) {
  const { nodes, materials } = useGLTF('/heater.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.579, -0.006, -1.543]} scale={0.001}>
        <mesh geometry={nodes['Assem3_-_fan-2005'].geometry} material={materials['Material.002']} />
        <mesh geometry={nodes['Assem3_-_fan-2005_1'].geometry} material={materials['Material.001']} />
        <mesh geometry={nodes['Assem3_-_fan-2005_2'].geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/heater.glb')
