/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 HWM2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HWM2(props) {
  const { nodes, materials } = useGLTF('/HWM2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[0.361, -0.494, 0.187]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.001']} position={[0.361, -0.494, -0.184]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.001']} position={[-0.367, -0.494, 0.187]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.001']} position={[-0.367, -0.494, -0.184]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.002']} position={[0, 0.505, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.002']} position={[0, 0.549, 0]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.005']} position={[-0.013, 0.6, -0.13]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.005']} position={[-0.011, 0.6, -0.13]} />
      <group position={[0.249, 0.474, -0.01]} rotation={[0.152, -0.004, 0.002]}>
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.006']} position={[0.261, 0.656, -0.174]} rotation={[0.778, -0.013, -0.009]} scale={[0.29, 0.126, 0.29]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.006']} position={[-0.151, 0.663, -0.176]} rotation={[0.778, -0.013, -0.009]} scale={[0.29, 0.126, 0.29]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.006']} position={[-0.248, 0.664, -0.176]} rotation={[0.778, -0.013, -0.009]} scale={[0.29, 0.126, 0.29]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.logo.geometry} material={materials.logo} position={[0.086, 0.667, -0.207]} rotation={[0.739, 0, 0]} scale={0.035} />
      <mesh geometry={nodes.tWIN_HUB.geometry} material={materials['tWIN HUB']} position={[0.086, 0.651, -0.189]} rotation={[0.808, -0.007, -0.006]} scale={[0.042, 0.033, 0.033]} />
      <mesh geometry={nodes.WHITE_PART.geometry} material={materials['WHITE PART']} position={[0.086, 0.648, -0.185]} rotation={[0.816, -0.007, -0.006]} scale={[0.043, 0.035, 0.016]} />
      <mesh geometry={nodes.SPIN_CYCLE.geometry} material={materials['SPIN CYCLE']} position={[0.274, 0.616, -0.143]} rotation={[0.774, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.WASH_CYCLE.geometry} material={materials['WASH CYCLE']} position={[-0.245, 0.616, -0.143]} rotation={[0.774, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.WASH_LEVEL.geometry} material={materials['WASH LEVEL']} position={[-0.141, 0.616, -0.143]} rotation={[0.774, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.WATER_LEVEL.geometry} material={materials['WATER LEVEL']} position={[-0.4, 0.646, -0.179]} rotation={[0.774, -0.035, -0.112]} scale={0.054} />
      <mesh geometry={nodes['4804045'].geometry} material={materials['4804045']} position={[-0.174, 0.614, -0.146]} rotation={[0.738, 0, 0]} scale={0.014} />
      <mesh geometry={nodes['5525462'].geometry} material={materials['5525462']} position={[0.239, 0.614, -0.146]} rotation={[0.738, 0, 0]} scale={0.014} />
      <mesh geometry={nodes['timer-icon-512x512-vrl212i7'].geometry} material={materials['timer-icon-512x512-vrl212i7']} position={[-0.275, 0.614, -0.146]} rotation={[0.738, 0, 0]} scale={0.009} />
      <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} position={[0.261, 0.648, -0.184]} rotation={[0.727, -0.003, -0.007]} scale={0.043} />
      <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[-0.152, 0.653, -0.185]} rotation={[0.727, -0.003, -0.007]} scale={0.043} />
      <mesh geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} position={[-0.248, 0.655, -0.186]} rotation={[0.727, -0.003, -0.007]} scale={0.043} />
    </group>
  )
}

useGLTF.preload('/HWM2.glb')
